import { useState } from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'


import Header from '../../components/Header/Header'
import EditProfile from '../../components/Profile/EditProfile'
import History from '../../components/Profile/History'

import { GET_USER, GET_HISTORY } from '../../gql/user'

import graphQLClient from '../../config/graphql'
import useAuth from '../../hooks/useAuth';


export default function id({data, getHistory}) {
	const [loading, setLoading] = useState(true)
	const [user, setUser] = useState(null)
	const router = useRouter()


  const { auth, logout } = useAuth();
  const onLogout = () => {
    logout();
    router.push('/');
  }

  

  if(auth === null) return null


	return (

		<>
			<Head>
        <title>Editar perfil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
			<Header />
			
			<div className="container max-w-screen-lg flex flex-col">

				<div className="user-data">
					{ auth.id === data.id 
						? <EditProfile user={data} logout={onLogout} />
						: 'Hola otro usuario'
					}
				</div>

				<div className="md:max-w-screen-sm mx-auto mt-4">
					<h2 className="text-xl">Historial de Compras</h2>

					{
						getHistory !== null && getHistory.map((product, index) => <History key={index} {...product} /> )

					}

					
				</div>
				
			</div>

			
		</>

	)
}

id.getInitialProps = async (ctx) => {
	const {id} = ctx.query;
	const {getUser} = await GET_USER(id)
	const {getHistory} = await GET_HISTORY(id)


	return {
		data: getUser || null,
		getHistory		
	}

}