import React, { useState } from 'react';
import Head from 'next/head'
import { useRouter } from 'next/router'

import RegisterForm from '../components/Auth/RegisterForm';
import LoginForm from '../components/Auth/LoginForm';

import useAuth from '../hooks/useAuth'

export default function Auth() {

  const [showLogin, setShowLogin] = useState(true);
  const router = useRouter()

  const { auth } = useAuth()

  if(auth?.email){
    router.push('/')
  }

  return (
    <>

      <Head>
        <title>{showLogin ? 'Iniciar sesion' : 'Registrate aquí'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto flex flex-col text-center  h-screen items-center justify-center">

        <div className="container-form">
          {
            showLogin ? <LoginForm /> : <RegisterForm setShowLogin={setShowLogin} />
          }
        </div>

        <div className="change-form">
          <div>
            {
              showLogin ? (
                <div className="mb-3">
                  <p className="text-gray-900 text-base">
                    ¿No tienes cuenta?
                    <span className="text-blue-900 text-base cursor-pointer" onClick={() => setShowLogin(!showLogin)} >Crea tu cuenta</span>
                    
                  </p>
                </div>
              ) : (
                <>
                  <div className="mb-3">
                  <p className="text-gray-900 text-base">
                    Entra con tu cuenta
                    
                    <span className="text-blue-900 text-base cursor-pointer" onClick={() => setShowLogin(!showLogin)} > Iniciar sesión</span>
                    
                  </p>
                </div>
                </>
              )
            }
          </div>
        </div>

      </div>
    </>
  );
};
