import Head from 'next/head'
import { useRouter } from 'next/router'

import Image from 'next/image'
import styles from '../styles/Home.module.css'

import useAuth from '../hooks/useAuth'

import Header from '../components/Header/Header'
import AllProducts from '../components/Product/AllProducts'

export default function Home() {

  const router = useRouter()

  const { auth } = useAuth()


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      
      <main className="mx-auto md:max-w-screen-sm flex flex-col mx-auto">
        <AllProducts />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
