import Head from 'next/head'
import { useRouter } from 'next/router'

import Image from 'next/image'
import styles from '../styles/Home.module.css'

import useAuth from '../hooks/useAuth'

import Header from '../components/Header/Header'
import AllProducts from '../components/Product/AllProducts'

export default function Home() {

  const router = useRouter()

  const { auth } = useAuth()


  return (
    <div>
      <Head>
        <title>Inicio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      
      <main className="mx-auto md:max-w-screen-sm flex flex-col mx-auto">
        <h2 className="text-2xl text-black border-b-2 border-gray-200">Productos en stock</h2>
        <AllProducts listAdminPage={false} showAll={false}/>
      </main>

    </div>
  )
}
