import Head from 'next/head'
import { useRouter } from 'next/router'


import useAuth from '../../hooks/useAuth'

import Header from '../../components/Header/Header'
import AllProducts from '../../components/Product/AllProducts'

export default function Home() {

  const router = useRouter()

  const { auth } = useAuth()


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      
      <main className="mx-auto md:max-w-screen-sm flex flex-col mx-auto">
        <AllProducts listAdminPage={true} showAll={true}/>
      </main>
    </div>
  )
}
